language: java
notifications:
  email:
    recipients: loganwaldman@gmail.com
    on-sucsess: change
    on_failure: always # These are both using defaults, prob. can be removed

  irc:
    channels: "irc.esper.net#johnsmith0508"
    on_success: always # default: always
    on_failure: change # default: always
    template:
        - "build #%{build_number} of %{repository_name} just finished after %{duration}, final result being: %{result}"
        - "Change view: %{compare_url} Build Detaild: %{build_url}"